# Generated by Django 3.1.5 on 2021-04-13 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210413_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(blank=True, null=True, verbose_name='create date')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cars', to='api.car')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='users', to='api.user')),
            ],
        ),
    ]
